name: Ruby Testing
on:
  pull_request:
  push:
    branches:
    - master
env:
  RAILS_ENV: test
  BUNDLE_WITHOUT: journald:development:console:libvirt
  DATABASE_URL: postgresql://postgres:@localhost/test
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
  test_ruby:
    runs-on: ubuntu-latest
    needs: rubocop
    services:
      postgres:
        image: postgres:12.1
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        foreman-core-branch: [2.5-stable, develop]
        ruby-version: [2.7]
        node-version: [12]
    steps:
      - run: sudo apt-get install build-essential libcurl4-openssl-dev zlib1g-dev libpq-dev
      - uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          ref: ${{ matrix.foreman-core-branch }}
      - uses: actions/checkout@v2
        with:
          path: foreman_statistics
      - name: Setup Bundler
        run: |
          echo "gem 'foreman_statistics', path: './foreman_statistics'" > bundler.d/foreman_statistics.local.rb
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Setup Node
        if: github.event_name != 'push'
        uses: actions/setup-node@v1
        with:
          node-version:  ${{ matrix.node-version }}
      - name: Prepare test DB
        if: github.event_name != 'push'
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
      - name: Run plugin tests
        if: github.event_name != 'push'
        run: |
          bundle exec rake test:foreman_statistics
